import * as Print from "expo-print";

import type { InventoryAnalyticsSummary } from "../types/inventoryAnalytics";
import type {
  ExportedReport,
  ExportReportType,
} from "../types/exportReport";
import type { Product } from "../types/product";
import type { TransactionHistoryItem } from "../types/transactionHistory";

function escapeHtml(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }

  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    maximumFractionDigits: 2,
  }).format(value);
}

function formatDateTime(value: string): string {
  return new Date(value).toLocaleString("en-CA", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function createDocumentStyles(): string {
  return `
    <style>
      @page {
        margin: 28px;
      }

      * {
        box-sizing: border-box;
      }

      body {
        font-family: Helvetica, Arial, sans-serif;
        color: #1f2937;
        font-size: 11px;
        line-height: 1.45;
      }

      h1 {
        margin: 0;
        font-size: 24px;
        color: #111827;
      }

      h2 {
        margin-top: 26px;
        margin-bottom: 10px;
        font-size: 17px;
        color: #111827;
      }

      .subtitle {
        margin-top: 5px;
        color: #6b7280;
      }

      .meta {
        margin-top: 14px;
        color: #6b7280;
      }

      .summary-grid {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
        margin-top: 18px;
      }

      .summary-card {
        width: 48%;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 12px;
        background: #f9fafb;
      }

      .summary-label {
        font-size: 10px;
        text-transform: uppercase;
        color: #6b7280;
      }

      .summary-value {
        margin-top: 4px;
        font-size: 18px;
        font-weight: 700;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
      }

      th {
        background: #111827;
        color: #ffffff;
        text-align: left;
        padding: 7px;
        font-size: 9px;
      }

      td {
        border-bottom: 1px solid #e5e7eb;
        padding: 7px;
        vertical-align: top;
        font-size: 9px;
      }

      tr:nth-child(even) td {
        background: #f9fafb;
      }

      .positive {
        color: #15803d;
        font-weight: 700;
      }

      .negative {
        color: #b42318;
        font-weight: 700;
      }

      .footer {
        margin-top: 28px;
        padding-top: 10px;
        border-top: 1px solid #e5e7eb;
        color: #9ca3af;
        font-size: 9px;
      }
    </style>
  `;
}

function createHtmlDocument(
  title: string,
  body: string,
): string {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        ${createDocumentStyles()}
      </head>

      <body>
        <h1>${escapeHtml(title)}</h1>

        <div class="subtitle">
          SmartStock Analytics
        </div>

        <div class="meta">
          Generated:
          ${escapeHtml(
            new Date().toLocaleString("en-CA"),
          )}
        </div>

        ${body}

        <div class="footer">
          Generated by SmartStock Analytics
        </div>
      </body>
    </html>
  `;
}

async function generatePdf(
  reportType: ExportReportType,
  html: string,
  rowCount: number,
): Promise<ExportedReport> {
  const result =
    await Print.printToFileAsync({
      html,
    });

  return {
    fileName: `smartstock-${reportType}-${Date.now()}.pdf`,
    fileUri: result.uri,
    reportType,
    format: "pdf",
    rowCount,
    createdAt: new Date().toISOString(),
  };
}

export async function exportInventoryPdf(
  products: Product[],
): Promise<ExportedReport> {
  const totalUnits = products.reduce(
    (total, product) =>
      total + product.currentStock,
    0,
  );

  const totalCost = products.reduce(
    (total, product) =>
      total +
      product.currentStock *
        product.unitCost,
    0,
  );

  const totalRetail = products.reduce(
    (total, product) =>
      total +
      product.currentStock *
        product.unitPrice,
    0,
  );

  const lowStockCount = products.filter(
    (product) =>
      product.currentStock <=
      product.reorderLevel,
  ).length;

  const tableRows = products
    .map(
      (product) => `
        <tr>
          <td>${escapeHtml(product.name)}</td>
          <td>${escapeHtml(product.brand)}</td>
          <td>${escapeHtml(product.category)}</td>
          <td>${escapeHtml(product.barcode)}</td>
          <td>${product.currentStock}</td>
          <td>${product.reorderLevel}</td>
          <td>${formatCurrency(product.unitCost)}</td>
          <td>${formatCurrency(product.unitPrice)}</td>
        </tr>
      `,
    )
    .join("");

  const body = `
    <div class="summary-grid">
      <div class="summary-card">
        <div class="summary-label">
          Products
        </div>
        <div class="summary-value">
          ${products.length}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Stock Units
        </div>
        <div class="summary-value">
          ${totalUnits}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Inventory Cost
        </div>
        <div class="summary-value">
          ${formatCurrency(totalCost)}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Retail Value
        </div>
        <div class="summary-value">
          ${formatCurrency(totalRetail)}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Low Stock Products
        </div>
        <div class="summary-value">
          ${lowStockCount}
        </div>
      </div>
    </div>

    <h2>Inventory</h2>

    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Brand</th>
          <th>Category</th>
          <th>Barcode</th>
          <th>Stock</th>
          <th>Reorder</th>
          <th>Cost</th>
          <th>Price</th>
        </tr>
      </thead>

      <tbody>
        ${tableRows}
      </tbody>
    </table>
  `;

  return generatePdf(
    "inventory",
    createHtmlDocument(
      "Inventory Report",
      body,
    ),
    products.length,
  );
}

export async function exportTransactionsPdf(
  transactions: TransactionHistoryItem[],
): Promise<ExportedReport> {
  const tableRows = transactions
    .map((transaction) => {
      const stockChange =
        transaction.stockAfter -
        transaction.stockBefore;

      const stockClass =
        stockChange >= 0
          ? "positive"
          : "negative";

      return `
        <tr>
          <td>
            ${escapeHtml(
              transaction.productName,
            )}
          </td>

          <td>
            ${escapeHtml(
              transaction.transactionType,
            )}
          </td>

          <td>
            ${transaction.quantity}
          </td>

          <td class="${stockClass}">
            ${transaction.stockBefore}
            →
            ${transaction.stockAfter}
          </td>

          <td>
            ${formatCurrency(
              transaction.transactionValue,
            )}
          </td>

          <td>
            ${escapeHtml(
              transaction.source,
            )}
          </td>

          <td>
            ${escapeHtml(
              transaction.notes ?? "",
            )}
          </td>

          <td>
            ${escapeHtml(
              formatDateTime(
                transaction.createdAt,
              ),
            )}
          </td>
        </tr>
      `;
    })
    .join("");

  const body = `
    <div class="summary-grid">
      <div class="summary-card">
        <div class="summary-label">
          Transactions
        </div>

        <div class="summary-value">
          ${transactions.length}
        </div>
      </div>
    </div>

    <h2>Transaction History</h2>

    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Type</th>
          <th>Qty</th>
          <th>Stock</th>
          <th>Value</th>
          <th>Source</th>
          <th>Notes</th>
          <th>Date</th>
        </tr>
      </thead>

      <tbody>
        ${tableRows}
      </tbody>
    </table>
  `;

  return generatePdf(
    "transactions",
    createHtmlDocument(
      "Inventory Transaction Report",
      body,
    ),
    transactions.length,
  );
}

export async function exportAnalyticsPdf(
  analytics: InventoryAnalyticsSummary,
): Promise<ExportedReport> {
  const totalSales =
    analytics.dailyMetrics.reduce(
      (total, metric) =>
        total + metric.salesValue,
      0,
    );

  const totalStockIn =
    analytics.dailyMetrics.reduce(
      (total, metric) =>
        total + metric.stockInValue,
      0,
    );

  const totalDamage =
    analytics.dailyMetrics.reduce(
      (total, metric) =>
        total + metric.damageValue,
      0,
    );

  const dailyRows = analytics.dailyMetrics
    .map(
      (metric) => `
        <tr>
          <td>${escapeHtml(metric.date)}</td>
          <td>${formatCurrency(metric.salesValue)}</td>
          <td>${metric.salesUnits}</td>
          <td>${formatCurrency(metric.stockInValue)}</td>
          <td>${metric.stockInUnits}</td>
          <td>${formatCurrency(metric.damageValue)}</td>
          <td>${metric.damageUnits}</td>
        </tr>
      `,
    )
    .join("");

  const productRows =
    analytics.topProducts
      .map(
        (product, index) => `
          <tr>
            <td>${index + 1}</td>
            <td>${escapeHtml(product.productName)}</td>
            <td>${escapeHtml(product.brand)}</td>
            <td>${product.unitsSold}</td>
            <td>${formatCurrency(product.salesValue)}</td>
          </tr>
        `,
      )
      .join("");

  const categoryRows =
    analytics.topCategories
      .map(
        (category, index) => `
          <tr>
            <td>${index + 1}</td>
            <td>${escapeHtml(category.department)}</td>
            <td>${escapeHtml(category.category)}</td>
            <td>${category.unitsSold}</td>
            <td>${formatCurrency(category.salesValue)}</td>
          </tr>
        `,
      )
      .join("");

  const body = `
    <div class="summary-grid">
      <div class="summary-card">
        <div class="summary-label">
          Sales Value
        </div>
        <div class="summary-value">
          ${formatCurrency(totalSales)}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Stock Received
        </div>
        <div class="summary-value">
          ${formatCurrency(totalStockIn)}
        </div>
      </div>

      <div class="summary-card">
        <div class="summary-label">
          Damaged Inventory
        </div>
        <div class="summary-value">
          ${formatCurrency(totalDamage)}
        </div>
      </div>
    </div>

    <h2>Daily Analytics</h2>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Sales</th>
          <th>Sold Units</th>
          <th>Stock In</th>
          <th>Received</th>
          <th>Damage</th>
          <th>Damaged Units</th>
        </tr>
      </thead>

      <tbody>
        ${dailyRows}
      </tbody>
    </table>

    <h2>Top Products</h2>

    <table>
      <thead>
        <tr>
          <th>Rank</th>
          <th>Product</th>
          <th>Brand</th>
          <th>Units Sold</th>
          <th>Sales</th>
        </tr>
      </thead>

      <tbody>
        ${productRows}
      </tbody>
    </table>

    <h2>Top Categories</h2>

    <table>
      <thead>
        <tr>
          <th>Rank</th>
          <th>Department</th>
          <th>Category</th>
          <th>Units Sold</th>
          <th>Sales</th>
        </tr>
      </thead>

      <tbody>
        ${categoryRows}
      </tbody>
    </table>
  `;

  const rowCount =
    analytics.dailyMetrics.length +
    analytics.topProducts.length +
    analytics.topCategories.length;

  return generatePdf(
    "analytics",
    createHtmlDocument(
      "Analytics Report",
      body,
    ),
    rowCount,
  );
}